# Generated by Django 6.0.5 on 2026-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_customer_address_invoice_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='demo_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_demo_user',
            field=models.BooleanField(default=False),
        ),
    ]
