# Generated by Django 6.0.5 on 2026-05-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_userprofile_demo_created_at_userprofile_is_demo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='logo',
        ),
    ]
