# Generated by Django 6.0.5 on 2026-05-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='note',
        ),
    ]
