# Generated by Django 6.0.5 on 2026-05-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='state_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
