# Generated by Django 6.0.5 on 2026-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_companyprofile_state_code_companyprofile_state_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
